/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs/index'
import { Route as AdminCoursesCategoriesIndexRouteImport } from './routes/admin/courses/categories/index'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/admin/courses/',
  path: '/admin/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/admin/blogs/',
  path: '/admin/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesCategoriesIndexRoute =
  AdminCoursesCategoriesIndexRouteImport.update({
    id: '/admin/courses/categories/',
    path: '/admin/courses/categories/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/courses/categories': typeof AdminCoursesCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/courses/categories': typeof AdminCoursesCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/courses/categories/': typeof AdminCoursesCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/unauthorized'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/projects/$slug'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/projects'
    | '/student'
    | '/admin/blogs'
    | '/admin/courses'
    | '/admin/projects'
    | '/admin/users'
    | '/admin/courses/categories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/unauthorized'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/projects/$slug'
    | '/admin'
    | '/blog'
    | '/courses'
    | '/projects'
    | '/student'
    | '/admin/blogs'
    | '/admin/courses'
    | '/admin/projects'
    | '/admin/users'
    | '/admin/courses/categories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/unauthorized'
    | '/blog/$slug'
    | '/courses/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/blog/'
    | '/courses/'
    | '/projects/'
    | '/student/'
    | '/admin/blogs/'
    | '/admin/courses/'
    | '/admin/projects/'
    | '/admin/users/'
    | '/admin/courses/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminCoursesCategoriesIndexRoute: typeof AdminCoursesCategoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/categories/': {
      id: '/admin/courses/categories/'
      path: '/admin/courses/categories'
      fullPath: '/admin/courses/categories'
      preLoaderRoute: typeof AdminCoursesCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  BlogSlugRoute: BlogSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminCoursesCategoriesIndexRoute: AdminCoursesCategoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
