/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as ProjectsAdminRouteImport } from './routes/projects.admin'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as CoursesModulesAdminRouteImport } from './routes/courses.modules-admin'
import { Route as CoursesAdminRouteImport } from './routes/courses.admin'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BlogAdminRouteImport } from './routes/blog.admin'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CoursesCourseSlugModuleSlugRouteImport } from './routes/courses.$courseSlug.$moduleSlug'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAdminRoute = ProjectsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const CoursesModulesAdminRoute = CoursesModulesAdminRouteImport.update({
  id: '/modules-admin',
  path: '/modules-admin',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesAdminRoute = CoursesAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const BlogAdminRoute = BlogAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CoursesCourseSlugModuleSlugRoute =
  CoursesCourseSlugModuleSlugRouteImport.update({
    id: '/$courseSlug/$moduleSlug',
    path: '/$courseSlug/$moduleSlug',
    getParentRoute: () => CoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/admin': typeof CoursesAdminRoute
  '/courses/modules-admin': typeof CoursesModulesAdminRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/admin': typeof ProjectsAdminRoute
  '/about': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/courses/$courseSlug/$moduleSlug': typeof CoursesCourseSlugModuleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/admin': typeof CoursesAdminRoute
  '/courses/modules-admin': typeof CoursesModulesAdminRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/admin': typeof ProjectsAdminRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/courses/$courseSlug/$moduleSlug': typeof CoursesCourseSlugModuleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/courses/admin': typeof CoursesAdminRoute
  '/courses/modules-admin': typeof CoursesModulesAdminRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/admin': typeof ProjectsAdminRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/courses/$courseSlug/$moduleSlug': typeof CoursesCourseSlugModuleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/courses'
    | '/projects'
    | '/unauthorized'
    | '/blog/$slug'
    | '/blog/admin'
    | '/courses/$slug'
    | '/courses/admin'
    | '/courses/modules-admin'
    | '/projects/$slug'
    | '/projects/admin'
    | '/about'
    | '/blog/'
    | '/courses/'
    | '/dashboard'
    | '/projects/'
    | '/courses/$courseSlug/$moduleSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/blog/$slug'
    | '/blog/admin'
    | '/courses/$slug'
    | '/courses/admin'
    | '/courses/modules-admin'
    | '/projects/$slug'
    | '/projects/admin'
    | '/about'
    | '/blog'
    | '/courses'
    | '/dashboard'
    | '/projects'
    | '/courses/$courseSlug/$moduleSlug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/courses'
    | '/projects'
    | '/unauthorized'
    | '/blog/$slug'
    | '/blog/admin'
    | '/courses/$slug'
    | '/courses/admin'
    | '/courses/modules-admin'
    | '/projects/$slug'
    | '/projects/admin'
    | '/about/'
    | '/blog/'
    | '/courses/'
    | '/dashboard/'
    | '/projects/'
    | '/courses/$courseSlug/$moduleSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AboutIndexRoute: typeof AboutIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/admin': {
      id: '/projects/admin'
      path: '/admin'
      fullPath: '/projects/admin'
      preLoaderRoute: typeof ProjectsAdminRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/courses/modules-admin': {
      id: '/courses/modules-admin'
      path: '/modules-admin'
      fullPath: '/courses/modules-admin'
      preLoaderRoute: typeof CoursesModulesAdminRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/admin': {
      id: '/courses/admin'
      path: '/admin'
      fullPath: '/courses/admin'
      preLoaderRoute: typeof CoursesAdminRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/blog/admin': {
      id: '/blog/admin'
      path: '/admin'
      fullPath: '/blog/admin'
      preLoaderRoute: typeof BlogAdminRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/courses/$courseSlug/$moduleSlug': {
      id: '/courses/$courseSlug/$moduleSlug'
      path: '/$courseSlug/$moduleSlug'
      fullPath: '/courses/$courseSlug/$moduleSlug'
      preLoaderRoute: typeof CoursesCourseSlugModuleSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAdminRoute: typeof BlogAdminRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogAdminRoute: BlogAdminRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesAdminRoute: typeof CoursesAdminRoute
  CoursesModulesAdminRoute: typeof CoursesModulesAdminRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesCourseSlugModuleSlugRoute: typeof CoursesCourseSlugModuleSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesAdminRoute: CoursesAdminRoute,
  CoursesModulesAdminRoute: CoursesModulesAdminRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesCourseSlugModuleSlugRoute: CoursesCourseSlugModuleSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsAdminRoute: typeof ProjectsAdminRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsAdminRoute: ProjectsAdminRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AboutIndexRoute: AboutIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
